### ISSUE TITLE
Mostra câmera de escanear código QR mesmo sem necessidade

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-woocommerce#11]
Ao abrir o aplicativo através do fluxo web2app em um dispositivo móvel, mostra a hierarquia de telas até chegar na tela certa de pagamentos.

Deve mostrar apenas diretamente a tela de pagamento sem a necessidade da câmera/escanear código qr que aparece por alguns instantes.

Sendo que dentro do app já há suporte de pagamentos para lojas in-app, poderia seguir o mesmo fluxo na integração e abrir diretamente a tela da loja.

**Comment by AlexJuca** [comment]
Este é uma melhora para o app android e está independente do plugin woocommerce. Irei adicionar isso no jira. Fechando essa issue.

**Comment by amarildolucas** [comment]
@AlexJuca esta issue deve manter-se aberta até ser corrigida no fluxo. O problema parte e afeta sites no wordpress independente da base de código. Assim que corrigida na carteira sem afetar o fluxo do wordpress pode ser comentada aqui para testes.

**Comment by amarildolucas** [comment]
@AlexJuca este bug foi corrigido e testado em produção. Como dito no comentário acima, tudo que envolve o fluxo é geral e um bug do fluxo envolvido. Sendo que este problema foi corrigido e não afeta mais a leitura do código qr nas integrações do comerciante, esta issue poderá ser fechada.
