### ISSUE TITLE
Url universal para pagamento errada

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-woocommerce#19]
Quando tento comprar um produto através do smartphone após clicar no botão de pagamento da KAMBA a carteira não abre e sou direcionado para esta URL.

Estou tentando comprar um produto no site da Sheshe Store LDA.

A comerciante possui o mesmo problema ao testar a integração na sua própria loja, logo devemos corrigir pois a loja não está funcional. 

https://checkout.usekamba.com/v1/pay?mID=b0f7ec2f-83bd-4b0f-aa31-13e4ac04c92a&chID=b0f7ec2f-83bd-4b0f-aa31-13e4ac04c92a

**Comment by AlexJuca** [comment]
Issue foi resolvida.
