### ISSUE TITLE
Código de pagamento não encontrado

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-woocommerce#3]
Ao digitalizar o código de pagamento QR para finalizar a compra no site https://sheshe-store.com/kamba-checkout o App retorna sempre **código de pagamento não encontrado**.

**Comment by AlexJuca** [comment]
Este problema ocorreu devido a data da expiração da ApiKey da loja em questão. Devemos alterar essa data de expiração em production para ser no mínimo um ano depois da criação da conta.

**Comment by AlexJuca** [comment]
Acredito que devemos usar rotação de ApiKeys de um ano e dá um périodo de graça de 3 meses para o merchant actualizar os ApiKeys em production. Se não renovar as ApiKeys não receberá pagamentos.
