### ISSUE TITLE
Utilidade do botão "Clica para pagar com KAMBA"?

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-woocommerce#4]
O botão poderá ser removido do fluxo visto que não possui utilidade no processo do pagamento nesta versão da integração.

http://g.recordit.co/bubXob5MsL.gif

**Comment by AlexJuca** [comment]
A ideia por de tras deste botão é permitir que o usuário paga usando sua carteira em situações que ele não pode escanear o código QR porque está navegando no site através do telemóvel. Irei esconder o botão caso o usuário esteja no PC e apenas mostrar quando estiver navegando usando um smartphone.

**Comment by amarildolucas** [comment]
No caso este fluxo deve se comportar de acordo o dispositivo. Se o checkout foi carregado numa página web em um computador não aparecer o botão por não ser necessário (quebra usabilidade) ou se for aberto em um dispositivo móvel também deverá comportar-se de acordo, ou seja, disponibilizando o botão e abrindo o aplicativo diretamente (tela pagamento comerciante) conforme o dispositivo.

**Comment by amarildolucas** [comment]
Enquanto não temos este suporte podemos simplesmente remover até ser adicionado como task e então ser feito um deploy com este update de fluxo melhorado.

**Comment by amarildolucas** [comment]
@AlexJuca sendo esse fluxo parte oficial do checkout woo, está agora fechado e deverá ser continuada a discussão na issue "melhorias de design para o kamba qr".
