### ISSUE TITLE
Imagem (bandeira) Kamba muito grande na página de checkou

### ISSUE THREAD

**Issue by JoseCage** [usekamba/kamba-woocommerce#6]
Fiz o cadastro na plataforma (como comerciante) e ao testar reparei que na página de **Checkout** a imagem que aparece ao lado da opção pagar com Kamba é ligeiramente maior que o padrão das bandeiras de pagamento.

![test-pgaar-kamba](https://user-images.githubusercontent.com/4200487/47421167-f23d8c00-d777-11e8-8fbe-5ad1d368f684.png)

**Comment by AlexJuca** [comment]
Obrigado pela observação @JoseCage, iremos adicionar um que segue os padrões existentes. O @JoseCage terá tempo para conversar comigo num live sobre a experiência da integração entre outras coisas? Podemos fazer uma call no hangouts.

**Comment by JoseCage** [comment]
> Obrigado pela observação @JoseCage, iremos adicionar um que segue os padrões existentes. O @JoseCage terá tempo para conversar comigo num live sobre a experiência da integração entre outras coisas? Podemos fazer uma call no hangouts.

Para quando pretende?

Se for no horário de almoço sim, dá-me jeito.

**Comment by JoseCage** [comment]
Por outro lado, @AlexJuca ao tentar proceder ao Checkout depois de escolher o Kamba mostra um alerta de erro no servidor. O que não aparece caso eu escolha outra opção.

![test-pgaar-kamba-error](https://user-images.githubusercontent.com/4200487/47423125-316ddc00-d77c-11e8-9b5f-17dff5d6d71f.png)

**Comment by AlexJuca** [comment]
@JoseCage Pode ser no horário do seu almoço mesmo. Sobre o problema do server, há algumas pendências no plugin e especial a documentação. Hoje irei actualizar o plugin e a documentação e deixar claro os passos necessários para integrar o plugin woocommerce da Usekamba. 

Quando estiver pronto para conversar no hangouts poderá enviar o link do hangouts.

**Comment by amarildolucas** [comment]
@JoseCage esta issue já foi aberta anteriormente e está em progresso no link abaixo, por este motivo iremos fechar essa e manter tudo concentrado em um único lugar. Fica a vontade e acompanhar as atualizações no link abaixo:

https://github.com/usekamba/kamba-woocommerce/issues/2
